---
cache:
  - cargo
  - yarn
matrix:
  include:
    - before_install:
        - "curl https://sh.rustup.rs -sSf > /tmp/rustup.sh"
        - "sh /tmp/rustup.sh -y"
        - 'export PATH="$HOME/.cargo/bin:$PATH"'
        - 'source "$HOME/.cargo/env"'
        - "node -v"
        - "yarn -v"
        - yarn
      language: node_js
      node_js:
        - node
        - 10
        - 9
        - 8
    - language: rust
      rust:
        - stable
        - beta
        - nightly
      script:
        - "cargo build --verbose --all"
        - "cargo test --verbose --all"
os:
  - osx
  - linux
