---
cache:
  - cargo
  - yarn
matrix:
  include:
    - before_install:
        - "curl https://sh.rustup.rs -sSf > /tmp/rustup.sh"
        - "sh /tmp/rustup.sh -y"
        - 'export PATH="$HOME/.cargo/bin:$PATH"'
        - 'source "$HOME/.cargo/env"'
        - "node -v"
        - "yarn -v"
        - yarn
      language: node_js
    - language: rust
      script:
        - "cargo build --verbose --all"
        - "cargo test --verbose --all"
#os:
#  - osx
#  - linux
rust:
  - stable
  - nightly
node_js:
  - node
  - 10
  - 9
  - 8
