[package]
name = "graphql_rs_native"
version = "0.0.1"
authors = ["Nigel Schuster <Neitsch@users.noreply.github.com>"]
license = "MIT"

[lib]
name = "graphql_rs_native"

[dependencies]
nom = "4.2.3"
serde_derive = "1.0.80"
serde = "1.0.80"